### ISSUE TITLE
Cannot read property 'slug' of undefined

### ISSUE THREAD

**Issue by tommotaku** [maryamaljanabi/bestbags-nodejs-ecommerce#2]
I'm getting this error in home.ejs. How can I solve it?

```
TypeError: C:\Users\vaish\bestbags-nodejs-ecommerce\views\shop\home.ejs:52
    50|     <% for(let i=0; i<3; i++){ %>
    51|     <div class="col-lg-3 col-md-3 col-sm-12 text-center ml-2">
 >> 52|       <a class="title-link" href="/products/<%=categories[i].slug%>">
    53|         <img src="images/dept<%=i%>.jpg" alt="category" class="circle-img" />
    54|         <h4 class="mb-3 mt-3"><%=categories[i].title%></h4>
    55|       </a>

Cannot read property 'slug' of undefined
    at eval (eval at compile (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:109:39)
    at returnedFn (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:668:17)
    at tryHandleCache (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:254:36)
    at View.exports.renderFile [as engine] (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:485:10)
    at View.render (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\response.js:1008:7)
    at C:\Users\vaish\bestbags-nodejs-ecommerce\routes\index.js:20:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Mahmood-Hussain** [comment]
this is because they have not handled the case if there are no categories or projects.

Now the solution is seed the database which is in seedDB directory also you may receive there an import error use `const connectDB = require("../config/db");`  instead of `const connectDB = require("./config/db");` in category-seed.js

**Comment by Lihaas** [comment]
> this is because they have not handled the case if there are no categories or projects.
> 
> Now the solution is seed the database which is in seedDB directory also you may receive there an import error use `const connectDB = require("../config/db");` instead of `const connectDB = require("./config/db");` in category-seed.js

did but nothing is happened same error coming

**Comment by maryamaljanabi** [comment]
@Lihaas Hello, in order to run the application there are a few environmental variables that you need to set (please see the run section in the readme file). After you have successfully added your MongoDB Atlas connection string you need to navigate to the "seedDB" folder and run "npm category-seed.js" and "npm product-seed.js", this is to fill your empty MongoDB Atlas database. I've just fixed the paths in the seedDB files so they should work just fine now.
After doing these steps the application should work.

**Comment by ezolboo** [comment]
@maryamaljanabi I think you need to update the readme file to change  "npm category-seed.js" and "npm product-seed.js" to  "node category-seed.js" and "node product-seed.js"

npm was not working but node command worked

**Comment by maryamaljanabi** [comment]
> @maryamaljanabi I think you need to update the readme file to change "npm category-seed.js" and "npm product-seed.js" to "node category-seed.js" and "node product-seed.js"
> 
> npm was not working but node command worked

Oh I meant node, sorry about the typo, I just updated it. Thanks for letting me know.
