### ISSUE TITLE
HI! i found this error how can i solve

### ISSUE THREAD

**Issue by tntappmusa** [maryamaljanabi/bestbags-nodejs-ecommerce#20]
TypeError: C:\Users\vaish\bestbags-nodejs-ecommerce\views\shop\home.ejs:52
    50|     <% for(let i=0; i<3; i++){ %>
    51|     <div class="col-lg-3 col-md-3 col-sm-12 text-center ml-2">
 >> 52|       <a class="title-link" href="/products/<%=categories[i].slug%>">
    53|         <img src="images/dept<%=i%>.jpg" alt="category" class="circle-img" />
    54|         <h4 class="mb-3 mt-3"><%=categories[i].title%></h4>
    55|       </a>

Cannot read property 'slug' of undefined
    at eval (eval at compile (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:109:39)
    at returnedFn (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:668:17)
    at tryHandleCache (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:254:36)
    at View.exports.renderFile [as engine] (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\ejs\lib\ejs.js:485:10)
    at View.render (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\vaish\bestbags-nodejs-ecommerce\node_modules\express\lib\response.js:1008:7)
    at C:\Users\vaish\bestbags-nodejs-ecommerce\routes\index.js:20:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by tntappmusa** [comment]
error due to mongoose error and not project's thanks
